createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: job
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.url | sub("%20"; "-"; "g") | sub("/"; "-"; "g") | .[:-1]'
          title: .displayName
          blueprint: '"job"'
          properties:
            jobName: .fullName
            url: .url
            jobStatus: . | split(\".\") | last
            timestamp: .time
  - kind: build
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.fullDisplayName | sub(" "; "-"; "g") | sub("#"; ""; "g")'
          title: .displayName
          blueprint: '"build"'
          properties:
            buildStatus: .result,
            buildUrl: .url,
            buildDuration: .duration,
            timestamp: .timestamp
          relations:
            job: '.source | tostring | sub("%20"; "-"; "g") | sub("/"; "-"; "g") | .[:-1]'