createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: job
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.url | sub("%20"; "-"; "g") | sub("/"; "-"; "g") | .[:-1]'
          title: .data.displayName
          blueprint: '"job"'
          properties:
            jobName: .data.fullName
            url: .url
            jobStatus: .type | split(\".\") | last
            timestamp: .time
  - kind: build
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.data.fullDisplayName | sub(" "; "-"; "g") | sub("#"; ""; "g")'
          title: .data.displayName
          blueprint: '"build"'
          properties:
            buildStatus: .data.result,
            buildUrl: .url,
            buildDuration: .data.duration,
            timestamp: .data.timestamp
          relations:
            job: '.source | tostring | sub("%20"; "-"; "g") | sub("/"; "-"; "g") | .[:-1]'